### ISSUE TITLE
1.6.0無法使用

### ISSUE THREAD

**Issue by tiqit2** [qqaatw/JciHitachiHA#66]
![image](https://github.com/qqaatw/JciHitachiHA/assets/24760187/46758ab1-928f-4195-b696-3144dd26d99f)

更新到1.6.0後還是一樣使用
Home Assistant Core : 2023.11.2

_Originally posted by @tiqit2 in https://github.com/qqaatw/JciHitachiHA/issues/63#issuecomment-1872477084_

**Comment by Naanoda** [comment]
插件更新後應重新啟動HA而非重新載入.

**Comment by peterface8888** [comment]
我重開機, 並重新登入, Incorrect email or password

**Comment by qqaatw** [comment]
I believe many use HACS to install or upgrade to `1.6.0`, which is definitely not a method mentioned in the configuration instruction.

While HACS is a convenient way to download and install things in Home Assistant, it can be very problematic when the backend involves big package updates. Users solely relying on HACS to install things usually do not have the ability to check the file integrity and the versions of backend dependencies. **Sorry, we're not going to deal with issues caused by this kind of problems, and if anyone is willing to share your experience on how to correctly upgrade `JciHitachiHA` using HACS, it would be highly appreciated.**

For anyone having issues with login, please take a look at the `System Status` badge on the readme (or you can see below). If it is green, that means the Hitachi cloud has no issue at the latest check, which happens at 8:00 AM GMT+8 everyday. 

![System Status](https://github.com/qqaatw/LibJciHitachi/actions/workflows/Status.yml/badge.svg)

**Comment by WuAmos** [comment]
> 我重開機, 並重新登入, Incorrect email or password

我也是，改用configuration.yaml 設定後則可正常登入
